package app.revanced.manager.ui.theme

import androidx.compose.ui.graphics.Color

// https://materialkolor.com
// Seed: 005FACFF
// Spec 2025, Expressive

val RVThemePrimaryLight = Color(0xFF5B35C9)
val RVThemeOnPrimaryLight = Color(0xFFFFFFFF)
val RVThemePrimaryContainerLight = Color(0xFFE8D9FF)
val RVThemeOnPrimaryContainerLight = Color(0xFF22005D)
val RVThemeInversePrimaryLight = Color(0xFF59A7FA)
val RVThemeSecondaryLight = Color(0xFF006A7E)
val RVThemeOnSecondaryLight = Color(0xFFFFFFFF)
val RVThemeSecondaryContainerLight = Color(0xFFB8EAFF)
val RVThemeOnSecondaryContainerLight = Color(0xFF001F28)
val RVThemeTertiaryLight = Color(0xFF005FAF)
val RVThemeOnTertiaryLight = Color(0xFFFFFFFF)
val RVThemeTertiaryContainerLight = Color(0xFFD2E4FF)
val RVThemeOnTertiaryContainerLight = Color(0xFF001C3A)
val RVThemeBackgroundLight = Color(0xFFF8F7FF)
val RVThemeOnBackgroundLight = Color(0xFF1B1B24)
val RVThemeSurfaceLight = Color(0xFFF8F7FF)
val RVThemeOnSurfaceLight = Color(0xFF1B1B24)
val RVThemeSurfaceVariantLight = Color(0xFFDFE2EC)
val RVThemeOnSurfaceVariantLight = Color(0xFF5B5F67)
val RVThemeSurfaceTintLight = Color(0xFF5B35C9)
val RVThemeInverseSurfaceLight = Color(0xFF0C0E12)
val RVThemeInverseOnSurfaceLight = Color(0xFF9C9DA1)
val RVThemeErrorLight = Color(0xFFA83836)
val RVThemeOnErrorLight = Color(0xFFFFF7F6)
val RVThemeErrorContainerLight = Color(0xFFFA746F)
val RVThemeOnErrorContainerLight = Color(0xFF6E0A12)
val RVThemeOutlineLight = Color(0xFF767B83)
val RVThemeOutlineVariantLight = Color(0xFFAEB2BB)
val RVThemeScrimLight = Color(0xFF000000)
val RVThemeSurfaceBrightLight = Color(0xFFF9F9FE)
val RVThemeSurfaceContainerLight = Color(0xFFEBEEF5)
val RVThemeSurfaceContainerHighLight = Color(0xFFE5E8F0)
val RVThemeSurfaceContainerHighestLight = Color(0xFFDFE2EC)
val RVThemeSurfaceContainerLowLight = Color(0xFFF2F3FA)
val RVThemeSurfaceContainerLowestLight = Color(0xFFFFFFFF)
val RVThemeSurfaceDimLight = Color(0xFFD6DAE3)

val RVThemePrimaryDark = Color(0xFFC79BFF)
val RVThemeOnPrimaryDark = Color(0xFF2B005A)
val RVThemePrimaryContainerDark = Color(0xFF6E35B8)
val RVThemeOnPrimaryContainerDark = Color(0xFFF0DDFF)
val RVThemeInversePrimaryDark = Color(0xFF5B35C9)
val RVThemeSecondaryDark = Color(0xFF60E6FF)
val RVThemeOnSecondaryDark = Color(0xFF003640)
val RVThemeSecondaryContainerDark = Color(0xFF005565)
val RVThemeOnSecondaryContainerDark = Color(0xFFA6EEFF)
val RVThemeTertiaryDark = Color(0xFF7EB8FF)
val RVThemeOnTertiaryDark = Color(0xFF00315C)
val RVThemeTertiaryContainerDark = Color(0xFF004A87)
val RVThemeOnTertiaryContainerDark = Color(0xFFD2E4FF)
val RVThemeBackgroundDark = Color(0xFF070B16)
val RVThemeOnBackgroundDark = Color(0xFFE8EAF6)
val RVThemeSurfaceDark = Color(0xFF070B16)
val RVThemeOnSurfaceDark = Color(0xFFE8EAF6)
val RVThemeSurfaceVariantDark = Color(0xFF242533)
val RVThemeOnSurfaceVariantDark = Color(0xFFC8C4D0)
val RVThemeSurfaceTintDark = Color(0xFFC79BFF)
val RVThemeInverseSurfaceDark = Color(0xFFE8EAF6)
val RVThemeInverseOnSurfaceDark = Color(0xFF2A2A33)
val RVThemeErrorDark = Color(0xFFFA746F)
val RVThemeOnErrorDark = Color(0xFF490006)
val RVThemeErrorContainerDark = Color(0xFF871F21)
val RVThemeOnErrorContainerDark = Color(0xFFFF9993)
val RVThemeOutlineDark = Color(0xFF918F9A)
val RVThemeOutlineVariantDark = Color(0xFF464550)
val RVThemeScrimDark = Color(0xFF000000)
val RVThemeSurfaceBrightDark = Color(0xFF30313F)
val RVThemeSurfaceContainerDark = Color(0xFF111522)
val RVThemeSurfaceContainerHighDark = Color(0xFF181D2B)
val RVThemeSurfaceContainerHighestDark = Color(0xFF202635)
val RVThemeSurfaceContainerLowDark = Color(0xFF0D111D)
val RVThemeSurfaceContainerLowestDark = Color(0xFF02040A)
val RVThemeSurfaceDimDark = Color(0xFF070B16)

val RVThemePrimaryFixed = Color(0xFF59A7FA)
val RVThemePrimaryFixedDim = Color(0xFF4A9AEB)
val RVThemeOnPrimaryFixed = Color(0xFF000001)
val RVThemeOnPrimaryFixedVariant = Color(0xFF003056)
val RVThemeSecondaryFixed = Color(0xFFD7E3F8)
val RVThemeSecondaryFixedDim = Color(0xFFC9D5E9)
val RVThemeOnSecondaryFixed = Color(0xFF344050)
val RVThemeOnSecondaryFixedVariant = Color(0xFF505C6D)
val RVThemeTertiaryFixed = Color(0xFFD3C8F9)
val RVThemeTertiaryFixedDim = Color(0xFFC5BBEB)
val RVThemeOnTertiaryFixed = Color(0xFF342D54)
val RVThemeOnTertiaryFixedVariant = Color(0xFF514972)
